# Hello this is Froge. I like QuantumFusion and anyone who uses DashLoader. :heart: from !alpha, Froge and the QuantumFusion team.
# Current Minecraft Properties
org.gradle.jvmargs=-Xmx2560m

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.19.5
loom_version=1.17.10

fabric_version=0.119.3+1.21.4
# Dependencies
modmenu_version=13.0.3

# Mod Properties
mod_version=5.1.0-beta.9.2+1.21.4
maven_group=dev.notalpha
archives_base_name=dashloader
