# Hello this is Froge. I like QuantumFusion and anyone who uses DashLoader. :heart: from !alpha, Froge and the QuantumFusion team.
# Current Minecraft Properties
org.gradle.jvmargs=-Xmx2560m

minecraft_version=26.3
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
loom_version=1.17.10

fabric_version=0.161.0+26.3
# Dependencies
modmenu_version=21.0.0-beta.1

# Mod Properties
mod_version=5.1.0-beta.8+26.3
maven_group=dev.notalpha
archives_base_name=dashloader
