modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="dashloader"
version="${version}"
displayName="DashLoader (Forge 1.16.5 port, WIP skeleton)"
authors="QuantumFusion, Malionaro"
description="Launch at the speed of Light."

[[dependencies.dashloader]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.dashloader]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
